openapi: 3.0.3
info:
  title: Auth Service API
  description: Authentication and User Registration
  version: 1.0.0

servers:
  - url: http://localhost:3001/api

tags:
  - name: Auth

paths:

  /auth/login:
    post:
      tags: [Auth]
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        200:
          description: JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'

  /auth/register:
    post:
      tags: [Auth]
      summary: User registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        201:
          description: User created

components:

  schemas:

    LoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string

    RegisterRequest:
      type: object
      properties:
        email:
          type: string
        username:
          type: string
        password:
          type: string

    AuthResponse:
      type: object
      properties:
        token:
          type: string
