openapi: 3.0.3
info:
  title: Dungeon Service API
  description: Dungeon runs and room management
  version: 1.0.0

servers:
  - url: http://localhost:3005/api

tags:
  - name: Dungeons

paths:

  /dungeons/start:
    post:
      tags: [Dungeons]
      summary: Start a dungeon run
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StartDungeonRequest'
      responses:
        201:
          description: Dungeon run created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DungeonRun'

  /dungeons/{runId}:
    get:
      tags: [Dungeons]
      summary: Get dungeon run
      parameters:
        - $ref: '#/components/parameters/RunId'
      responses:
        200:
          description: Dungeon run
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DungeonRun'

  /dungeons/{runId}/choices:
    get:
      tags: [Dungeons]
      summary: Get available room choices
      parameters:
        - $ref: '#/components/parameters/RunId'
      responses:
        200:
          description: Available room choices
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoomChoices'

  /dungeons/{runId}/choose:
    post:
      tags: [Dungeons]
      summary: Choose next room from available options
      parameters:
        - $ref: '#/components/parameters/RunId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChooseRoomRequest'
      responses:
        200:
          description: Room chosen and entered

  /dungeons/{runId}/finish:
    post:
      tags: [Dungeons]
      summary: Finish dungeon run
      parameters:
        - $ref: '#/components/parameters/RunId'
      responses:
        200:
          description: Dungeon completed

components:

  parameters:
    RunId:
      name: runId
      in: path
      required: true
      schema:
        type: string

  schemas:

    StartDungeonRequest:
      type: object
      properties:
        heroId:
          type: string

    DungeonRun:
      type: object
      properties:
        runId:
          type: string
        heroId:
          type: string
        status:
          type: string
        position:
          $ref: '#/components/schemas/Position'
        rooms:
          type: array
          items:
            $ref: '#/components/schemas/DungeonRoom'

    Position:
      type: object
      properties:
        floor:
          type: integer
        room:
          type: integer

    DungeonRoom:
      type: object
      properties:
        floor:
          type: integer
        room:
          type: integer
        type:
          type: string
        monsterId:
          type: string

    RoomChoice:
      type: object
      properties:
        floor:
          type: integer
        room:
          type: integer
        type:
          type: string

    RoomChoices:
      type: object
      properties:
        choices:
          type: array
          items:
            $ref: '#/components/schemas/RoomChoice'
          minItems: 0
          maxItems: 2

    ChooseRoomRequest:
      type: object
      properties:
        choiceIndex:
          type: integer
          description: Index of the chosen room (0 or 1)
          enum: [0, 1]
