openapi: 3.0.3
info:
  title: User Service API
  description: User management
  version: 1.0.0

servers:
  - url: http://localhost:3002/api

tags:
  - name: Users

paths:

  /users:
    get:
      tags: [Users]
      summary: List users
      responses:
        200:
          description: Users list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'

  /users/{userId}:
    get:
      tags: [Users]
      summary: Get user details
      parameters:
        - $ref: '#/components/parameters/UserId'
      responses:
        200:
          description: User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    put:
      tags: [Users]
      summary: Update user
      parameters:
        - $ref: '#/components/parameters/UserId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserRequest'
      responses:
        200:
          description: User updated
    delete:
      tags: [Users]
      summary: Delete user
      parameters:
        - $ref: '#/components/parameters/UserId'
      responses:
        204:
          description: User deleted

components:

  parameters:
    UserId:
      name: userId
      in: path
      required: true
      schema:
        type: string
        format: uuid

  schemas:

    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
        username:
          type: string
        createdAt:
          type: string
          format: date-time

    UpdateUserRequest:
      type: object
      properties:
        email:
          type: string
        username:
          type: string
